### ISSUE TITLE
How to cap the maximum number of topics generated?

### ISSUE THREAD

**Issue by arikanev** [dborrelli/chat-intents#4]
Hi, how do I put a limit on the maximum number of topics to be generated? And a minimum? Is there a way to do this within the hyper parameter optimization?

Thanks,
Ari

**Comment by dborrelli** [comment]
Hi,
Yes, you can do this by setting the label_lower and label_upper parameters. Check out the tutorial notebook for an example: https://github.com/dborrelli/chat-intents/blob/main/notebooks/chatintents_tutorial.ipynb.

**Comment by arikanev** [comment]
Hi, it doesnt seem to work. I have label_upper = 15, and sometimes it generates upwards of 300 labels.

(BTW, great work!)
